version: 2.1
orbs:
  node: circleci/node@4.1.0
commands:
  setup-node-and-yarn-install:
    steps:
      - node/install:
          install-yarn: true
          node-version: latest
      - node/install-packages:
          pkg-manager: yarn
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - setup-node-and-yarn-install
      - run:
          name: Front-End Install 
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install 
          command: |
            npm run backend:install 
      - run:
          name: Front-End Build 
          command: |
            npm run frontend:build 
      - run:
          name: Back-End Build 
          command: |
            npm run backend:build
          
